### ISSUE TITLE
Document scores for BAD documents are marked as valid

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/Appraise#103]
**Describe the bug**
As Rebecca discovered, the document level scores from BAD documents are probably marked as valid in the expert.

**Comment by snukky** [comment]
Closing, this had been implemented here: [create_wmt22_tasks.py](https://github.com/AppraiseDev/Appraise/commit/e363fc36ba064eb5fc3a72bcbe2d547a0e9f91b8#diff-5f4b760c01d1be2a3f83fc0b5e9a212a34b0a6345db40425bc59e156d484ae56). The source of the bug was me not using the latest branch when generating batches :)

**Comment by kocmitom** [comment]
Thank you Roman for looking into this!
