### ISSUE TITLE
"Identified 0 task(s)" when creating a new campaign

### ISSUE THREAD

**Issue by st-vincent1** [AppraiseDev/Appraise#107]
**Describe the bug**
Attempting to create a new campaign outside of the given Examples fails as 0 tasks are identified during build (so the campaign can't be started).

**To Reproduce**
1. Follow installation and setup steps as in `INSTALL.md`
2. Create a minimal failing example:
- `mkdir BadExample`
- paste the following contents into `BadExample/manifest.json`:
```
{
    "CAMPAIGN_URL": "http://127.0.0.1:8000/dashboard/sso/",
    "CAMPAIGN_NAME": "badc",
    "CAMPAIGN_KEY": "badc",
    "CAMPAIGN_NO": 33,
    "REDUNDANCY": 1,

    "TASKS_TO_ANNOTATORS": [
        ["eng", "deu", "uniform", 10, 10]
    ],

    "TASK_TYPE": "Direct",
    "TASK_OPTIONS": "SQM"
}
```
- paste the following into `BadExample/batches.json`:

```
[
    {
        "items": [
            {
                "_block": 0,
                "_item": 0,
                "itemID": 0,
                "itemType": "BASE",
                "sourceID": "human_eval/test.batch1.de",
                "sourceText": "Ihnen ist klar, daß diese Sache mich meinen Job kosten kann.",
                "targetID": "human_eval/baseline.batch1.de",
                "targetText": "Dir ist klar, dass mich diese Entscheidung meinen Job kosten könnte."
            },
            {
                "_block": 0,
                "_item": 2,
                "itemID": 1,
                "itemType": "BASE",
                "sourceID": "human_eval/test.batch1.de",
                "sourceText": "Übrigens, bekommt ihr keine Angst, hier draußen zu leben?",
                "targetID": "human_eval/baseline.batch1.de",
                "targetText": "Übrigens, hast du keine Angst, hier draußen zu leben?"
            },
            {
                "_block": 0,
                "_item": 4,
                "itemID": 2,
                "itemType": "BASE",
                "sourceID": "human_eval/test.batch1.de",
                "sourceText": "Du stehst da, als würdest du dich nicht trauen, mir ein Geheimnis zu verraten.",
                "targetID": "human_eval/baseline.batch1.de",
                "targetText": "Du stehst da, als würdest du mir ein Geheimnis verraten, aber das tust du nicht."
            },
            {
                "_block": 0,
                "_item": 6,
                "itemID": 3,
                "itemType": "BASE",
                "sourceID": "human_eval/test.batch1.de",
                "sourceText": "Du lebst unter uns als ein ruhiger Farmjunge.",
                "targetID": "human_eval/baseline.batch1.de",
                "targetText": "Siehst du, du lebst unter uns als milder Bauernjunge."
            },
            {
                "_block": 0,
                "_item": 8,
                "itemID": 4,
                "itemType": "BASE",
                "sourceID": "human_eval/test.batch1.de",
                "sourceText": "Wasch sie im Brunnen, du wirst den Geruch der Klamotten lieben.",
                "targetID": "human_eval/baseline.batch1.de",
                "targetText": "Benutz den Springbrunnen, du wirst den Geruch der Kleider lieben."
            }
        ],
        "task": {
            "batchNo": 1,
            "batchSize": 5,
            "randomSeed": 42,
            "requiredAnnotations": 1,
            "sourceLanguage": "eng",
            "targetLanguage": "deu"
        }
    }
]
```
3. Create campaign `python manage.py StartNewCampaign BadExample/manifest.json     --batches-json BadExample/batches.json     --csv-output BadExample/output.csv` gives:
![image](https://user-images.githubusercontent.com/19303946/221805444-8b911275-0416-4920-84c4-3f8a27f90036.png)

**Expected behavior**
Something akin to what happens with Examples:
![image](https://user-images.githubusercontent.com/19303946/221805154-007e977b-05e8-4564-9b98-12ef510b9db6.png)

**Desktop (please complete the following information):**
I'm running python 3.10 on Ubuntu.

Thanks for any help. As a side question, what is the relationship between REDUNDANCY, NUMBER_OF_TASKS and NUMBER_OF_ANNOTATORS? What are the correct values for a campaign with 10 human annotators, where each one is given the full test set (task?) to annotate exactly once?

**Comment by cfedermann** [comment]
Quick note without having run this locally: you set batchSize to 5 but have
6 items in your JSON?

**Comment by st-vincent1** [comment]
Hi Christian,

Well spotted - I was editing down the manifest/batches files to form a minimal example, and made a mistake. With 5 items in the JSON the same error remains

**Comment by cfedermann** [comment]
I'll look into this towards the end of the week.

**Comment by cfedermann** [comment]
No, not yet, sorry. Busy with a new language release.

I will try to get back to you by the end of Friday…

**Comment by snukky** [comment]
Hi, I think this is just a misunderstanding of the requirements for `batches.json` and very likely a lack of documentation on our side :)
A single batch **must** consists of 100 items. Please ignore `batchSize` for now, it may be there for some historical reasons. Take a look at https://github.com/AppraiseDev/Appraise/blob/main/Examples/Direct/batches.json for an example for the Direct/SQM task.
With a single batch (i.e. 100 items), you then want `["eng", "deu", "uniform",  1, 1]` in `manifest.json`.

**Comment by snukky** [comment]
> As a side question, what is the relationship between REDUNDANCY, NUMBER_OF_TASKS and NUMBER_OF_ANNOTATORS? What are the correct values for a campaign with 10 human annotators, where each one is given the full test set (task?) to annotate exactly once?

"Number of tasks" is how many batches you have in `batches.json`. "Number of annotators" set the total number of user accounts. If "number of annotators" == "number of tasks" then 1 account has exactly 1 batch to annotate (=100 items). If, for example, "number of annotators" == 2x"number of tasks" then 1 account will have 2 batches (=200 items in total). (Note that "number of tasks" must be a multiplier of "number of annotators"). If you then, for example, set REDUNDANCY to 2, each annotator/account will have to annotate everything twice. 

In your scenario, where you want to have a test set annotated 10 times, I think I would personally create 10 campaigns, each campaign with "number of annotators" = 1, and if the entire test set is let's say 32 batches, I would set "number of tasks" = 32. There is probably a better way to achieve that, with a single campaign, but I never remember how batches are assigned to annotators, so that would be quicker and safer for me ^^

**Comment by snukky** [comment]
> If a single batch must consist of 100 items, then for a test set of e.g. 400 items do I need to make the batch list in batches.json a list of 4*100 items?

Just use 4 batches for your test set, each with 100 items.

> For an evaluation campaign where each sample gets annotated 10 times, given that my test set is 400 items (4 batches) now, with your further instructions, is this a correct understanding of the numbers?

Yes. `"REDUNDANCY": 1, "TASKS_TO_ANNOTATORS": [["eng", "deu", "uniform", 1, 4]],` will create you 1 account with all 4 batches. If you repeat that 10 times, you will have 10 identical accounts.

> Will this guarantee that each user sees all 400 samples rather than a subset of randomly picked with replacement 400 samples from the entire test set?

Yes. Appraise does not modify batches, it does not do sampling and it always preserves the ordering of items within a batch.

**Comment by st-vincent1** [comment]
Thanks!

Unfortunately, this is still not working for me. I'm attaching two batches/manifest pairs:
1. Single batch
2. Four batches

Neither set compiles correctly (same error as before) though I corrected the earlier batch size mistake; unfortunately, I can't debug this by myself as there's no error messages!

Could you please check if you can compile these in your build?

[bad_example_single.tar.gz](https://github.com/AppraiseDev/Appraise/files/10951321/bad_example_single.tar.gz)
[bad_example.tar.gz](https://github.com/AppraiseDev/Appraise/files/10951322/bad_example.tar.gz)

**Comment by snukky** [comment]
Both examples you provided worked for me. Can you setup a fresh DB (if you use the built-in DB, remove `db.sqlite3` and follow instructions from `INSTALL.md`), try again resetting campaign IDs in `manifest.json`s, and provide the full output here? Thanks.

For the sake of completeness, I used Python 3.8.10, branch 'release', WSL Ubuntu 20.04, but I don't think any of this should matter much.

**Comment by st-vincent1** [comment]
Great, looks like it was indeed some sort of DB cache giving me this error. After cloning the repo & running installs from scratch it worked for me too.

Thank you so much for your help & patience! It could be very useful for the future if the information about obligatory batch size of 100 was included somewhere in the documentation/examples!

**Comment by J22Melody** [comment]
Hi @snukky 

I have the same issue when creating a campaign for a human evaluation study for text-to-pose sign language translation. Concretely, I forked from what was done for WMT-SLT here:

https://github.com/J22Melody/iict-eval/tree/text2pose/human_evaluation/batches_text2pose

and then run:

`python manage.py StartNewCampaign ~/iict-eval/human_evaluation/batches_text2pose/text2poseSignsuisse.deu-sgg.manifest.json --batches-json  ~/iict-eval/human_evaluation/batches_text2pose/batches.text2pose.signsuisse.deu-sgg.ref.json  --csv-output ~/iict-eval/human_evaluation/batches_text2pose/output.csv`

I guess it is caused by some errors in the json files but there is no clear error message for me to investigate further. Could you spot anything suspicious when you eyeball the manifest and batches or try to run it in Appraise?

Our plan is similar: run 500 examples translations from German to DSGS in the Signsuisse test set, so I make 5 batches of 100 examples and in each batch 10 documents of 10 examples. I do not actually need document since the examples in Signsuisse are independent sentences, but I just followed what we did in WMT-SLT.
