### ISSUE TITLE
MQM/ESA duplicate document entries

### ISSUE THREAD

**Issue by zouharvi** [AppraiseDev/Appraise#140]
There are allegedly duplicate entries in the first document (reported by @martinpopel on EnCs WMT testrun).
Could be caused by [data generation here](https://github.com/zouharvi/error-span-annotations) or somehow interact with the duplication of the first item to fill 100 segments (likely when the documents are sorted again).

**Comment by martinpopel** [comment]
Details for debugging: It was the first document (after the tutorial) in http://172.211.57.127:80/dashboard/sso/engces0101/e60336ec/. The first and last sentence of the document was src="So anyway, since it does hold true here, to fix it..." trg="Takže každopádně, protože to platí zde, abych to opravil,..."
(I have just a screenshot and Appraise does not allow me to go back to the first document, so I include just few words of the sentence.)

Based on the context, I think the sentence was actually the last sentence of the document. It did not make sense as the first sentence. @zouharvi can you check the raw input files - if the duplication is not already there?

**Comment by zouharvi** [comment]
Fixed in [0f1044bed1447fb8a13788ad5730bd10aabc557b.](https://github.com/zouharvi/error-span-annotations/commit/0f1044bed1447fb8a13788ad5730bd10aabc557b)
